version: '2'

services:
    web:
        image: mat-dashboard:latest
        ports:
            - "8080:80"
        networks:
            - code-network
    mysql:
        image: mat-tempdb:latest
        networks:
            - code-network
    php:
        image: php:5.6-fpm-alpine
        volumes:
            - ./:/usr/share/nginx/html
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
