version: '2'

services:
    web:
        image: mat-dashboard:latest
        ports:
            - "8080:80"
        networks:
            - code-network
    mysql:
        image: mat-tempdb:latest
        ports:
            - "3306:3306"
        networks:
            - code-network
    php:
        image: bitnami/php-fpm:latest
        depends_on:
            - mysql
        volumes:
            - ./:/usr/share/nginx/html
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
